name: sns_pocketbase_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  ionicons: ^0.2.2
  loading_animation_widget: ^1.3.0
  multi_select_flutter: ^4.1.3
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pocketbase: ^0.19.1
  provider: ^6.1.2
  rounded_loading_button_plus: ^3.0.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/credentials.json
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-VariableFont_wght.ttf

